#!/usr/bin/env python3
"""Generate/check the current case inventory so audit counts cannot silently drift."""
import argparse
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from engine.roots import resolve       # noqa: E402
from engine.verify import is_verified_exact  # noqa: E402


OUT = os.path.join(ROOT, "eval", "SOURCE_INVENTORY.md")
QUOTE_AUDIT = os.path.join(ROOT, "eval", "QUOTE_AUDIT.json")


def quote_audit_scope_errors():
    """Keep the historical network-audit rows aligned with the current source inventory.

    The audit results themselves retain their original timestamp; this check only prevents deleted
    or newly added source ids from silently drifting out of the companion machine-readable file.
    """
    try:
        with open(QUOTE_AUDIT, encoding="utf-8") as f:
            audit = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        return ["cannot read eval/QUOTE_AUDIT.json: {}".format(exc)]
    current = {}
    for path in glob.glob(os.path.join(ROOT, "cases", "*.kb.json")):
        with open(path, encoding="utf-8") as f:
            current[os.path.basename(path)] = {s["id"] for s in json.load(f).get("sources", [])}
    audited = {name: {s.get("id") for s in report.get("sources", [])}
               for name, report in (audit.get("cases") or {}).items()}
    errors = []
    for name in sorted(set(current) | set(audited)):
        missing = sorted(current.get(name, set()) - audited.get(name, set()))
        removed = sorted(audited.get(name, set()) - current.get(name, set()))
        if missing or removed:
            errors.append("{} quote-audit scope differs: missing={} removed={}".format(
                name, missing, removed))
    return errors


def render():
    lines = [
        "# Current source inventory",
        "",
        "> Generated by `python scripts/source_inventory.py --write`. CI fails if stale.",
        "",
        "| Case | sources | positions | root records | confirmed root identities | position quotes exact | unadmitted support links |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    totals = [0, 0, 0, 0, 0, 0]
    for path in sorted(glob.glob(os.path.join(ROOT, "cases", "*.kb.json"))):
        with open(path, encoding="utf-8") as f:
            kb = json.load(f)
        res = resolve(kb)
        exact_positions = sum(1 for source in kb.get("sources", [])
                              if is_verified_exact((source.get("provenance") or {}).get("position")))
        values = [len(kb.get("sources", [])), len(kb.get("positions", [])),
                  len(kb.get("datasets", [])), len(res.get("confirmed_by", {})), exact_positions,
                  len(res.get("unadmitted_edges", []))]
        totals = [a + b for a, b in zip(totals, values)]
        lines.append("| `{}` | {} | {} | {} | {} | {} | {} |".format(
            os.path.basename(path), *values))
    lines += [
        "| **Total** | **{}** | **{}** | **{}** | **{}** | **{}** | **{}** |".format(*totals),
        "",
        "`root records` is the number of named evidence-base entities, not per-position coverage.",
        "Exact position quotes use the current hashed verifier. Unadmitted support links remain visible",
        "but contribute zero confirmed-root coverage.",
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    text = render()
    if args.write:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote eval/SOURCE_INVENTORY.md")
    if args.check:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print("stale eval/SOURCE_INVENTORY.md — run: python scripts/source_inventory.py --write")
            return 1
        scope_errors = quote_audit_scope_errors()
        if scope_errors:
            print("\n".join(scope_errors))
            return 1
        print("source inventory current")
    if not args.write and not args.check:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
